// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eetinfohbplcjzhkocwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVldGluZm9oYnBsY2p6aGtvY3dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNzM2NDksImV4cCI6MjA2ODc0OTY0OX0.I8dkAa7XX3Z4wrxittRZ_fTE_JjcZ955xQw4EoBCFBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});